name: churchapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2 # 사용하시는 SDK 버전에 맞게 설정

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # 이 버전 유지
  flip_card: ^0.6.0 # 이 버전 유지
  syncfusion_flutter_pdfviewer: ^29.1.38 # PDF 뷰어 패키지 추가 (최신 버전 확인)
  path_provider: ^2.1.5 # 파일 시스템 접근 패키지 추가 (최신 버전 확인)

  # 현재 SDK 버전 (^3.7.2)과 호환되는 webview_flutter 및 플랫폼별 구현체 패키지 버전
  # webview_flutter v4.3.0의 Dependencies 정보 기준 (pub.dev 확인)
  webview_flutter: ^3.0.4
  webview_flutter_android: ^2.10.4
  webview_flutter_wkwebview: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - img/MainBanner.png
    - img/BottomBanner.png
    - img/card_back_1.png
    - img/card_back_2.png
    - img/card_back_3.png
    - img/msg_250316.png
    - img/bus_schedule.png
    - img/church_logo.png
    - img/church_collage_placeholder.png
    - img/pastor_photo.png

    # <<< PDF 파일 폴더 경로 추가 >>>
    - church_weekly/
    
  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/pretendard/Pretendard-Regular.otf
        - asset: fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600