name: churchapp # 사용자님의 프로젝트 이름이 맞다면 이대로 사용
description: "A new Flutter project."
publish_to: 'none' # 필요 시 이 줄을 제거하세요.
version: 1.0.0+1

environment:
  sdk: ^3.7.2 # 사용하시는 SDK 버전에 맞게 설정

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flip_card: ^0.6.0 # <-- 들여쓰기를 flutter 및 cupertino_icons와 동일하게 수정

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - img/MainBanner.png
    - img/BottomBanner.png
    - img/card_back_1.png
    - img/card_back_2.png
    - img/card_back_3.png
    - img/msg_250316.png
  fonts:
    - family: Pretendard # 사용할 폰트 패밀리 이름 (임의 지정 가능, 여기서 'Pretendard'로 사용)
      fonts:
        - asset: fonts/pretendard/Pretendard-Regular.otf # 다운로드한 폰트 파일 경로
          # weight: 400 # 필요에 따라 두께 지정 (선택 사항)
        - asset: fonts/pretendard/Pretendard-Bold.otf # 볼드체 파일 경로 (있다면)
          weight: 700 # 볼드체 두께 지정
        # 필요한 다른 폰트 파일들도 이곳에 추가합니다.
        - asset: fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600